services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: /root/src
    tty: true
    environment:
      - PYTHONPATH=/root
    volumes:
      - ./src:/root/src
      - ./results:/root/results
      - ./app:/root/app
